jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      # This should go into custom primary image, here's only for the sake of explanation
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            apt-get update && apt-get install curl -y
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin


      # This should go into custom primary image, here's only for the sake of explanation
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose

      - setup_remote_docker

      - run:
          name: Build dockers
          command: |
            docker-compose build

      - run:
          command: >
            docker-compose run -d --name app-test -p 3000:3000 app-test
          name: Run application with FAST Orb

      - fast/run_security_tests:
          app_port: '3000'
          test_record_id: '3670'
          policy_id: '87'

orbs:
  fast: 'wallarm/fast@1.1.0'
version: 2.1


   #   - run:
   #       name: Run security tests
   #       command: |
   #         docker-compose up -d app-test \
   #         && docker-compose run --name fast -e CI_MODE=testing -e TEST_RUN_URI=http://app-test:3000 fast
